export const GUEST_LIST = [
  {
    name: "Haider",
    side: "Qasim",
    group: "Family",
    invitedCount: 1,
    inviteStatus: "Not sent",
    notes: "",
  },
  {
    name: "Phuphu / Bilal",
    side: "Qasim",
    group: "Family",
    invitedCount: 2,
    inviteStatus: "Maybe",
    notes: "Needs confirmation",
  },
  {
    name: "Dad Hura",
    side: "Qasim",
    group: "Family",
    invitedCount: 1,
    inviteStatus: "Maybe",
    notes: "Needs confirmation",
  },
  {
    name: "Ramtin",
    side: "Qasim",
    group: "Friends",
    invitedCount: 3,
    inviteStatus: "Sent",
    notes: "+2",
  },
  { name: "Ataollah", side: "Qasim", group: "Friends", invitedCount: 1, inviteStatus: "Sent", notes: "" },
  { name: "Arman", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Sherry", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Saahil and Rayed",
    side: "Qasim",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Sent",
    notes: "",
  },
  {
    name: "Canva peeps",
    side: "Qasim",
    group: "Friends",
    invitedCount: "",
    inviteStatus: "Sent",
    notes: "Group placeholder",
  },
  { name: "Urooj", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Abdullah",
    side: "Qasim",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Thinking",
    notes: "+1",
  },
  {
    name: "Karthik",
    side: "Qasim",
    group: "Friends",
    invitedCount: 4,
    inviteStatus: "Thinking",
    notes: "+3",
  },
  { name: "Ranjani", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Hareesh",
    side: "Qasim",
    group: "Friends",
    invitedCount: 1,
    inviteStatus: "Maybe",
    notes: "Probably not",
  },
  { name: "Shak", side: "Qasim", group: "Friends", invitedCount: 3, inviteStatus: "Sent", notes: "+2" },
  { name: "Shahid", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Ankit", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Hassan Shaikh",
    side: "Qasim",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Sent",
    notes: "+1",
  },
  { name: "Bassam", side: "Qasim", group: "Friends", invitedCount: 1, inviteStatus: "Sent", notes: "" },
  { name: "Zamzam", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Ashish", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Daniel Wong", side: "Qasim", group: "Friends", invitedCount: 1, inviteStatus: "Sent", notes: "" },
  { name: "David Lord", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Kiana",
    side: "Qasim",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Sent",
    seedResponse: "Declined",
    notes: "+1; declined and banned from Australia",
  },
  { name: "Ehsan", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  {
    name: "Ahmed",
    side: "Qasim",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Maybe",
    notes: "+1?",
  },
  { name: "Vishnu", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Dania", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Aishani", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Yash", side: "Qasim", group: "Friends", invitedCount: 2, inviteStatus: "Sent", notes: "+1" },
  { name: "Mom and Dad", side: "Moksha", group: "Family", invitedCount: 2, inviteStatus: "Not sent", notes: "" },
  {
    name: "Mayur Uncle",
    side: "Moksha",
    group: "Family",
    invitedCount: 3,
    inviteStatus: "Not sent",
    notes: "+2",
  },
  {
    name: "Khushboo Aunty",
    side: "Moksha",
    group: "Family",
    invitedCount: 4,
    inviteStatus: "Not sent",
    notes: "+3",
  },
  {
    name: "Sandeep Uncle",
    side: "Moksha",
    group: "Family",
    invitedCount: "",
    inviteStatus: "Not sent",
    notes: "+?",
  },
  {
    name: "Neetu Aunty",
    side: "Moksha",
    group: "Family",
    invitedCount: 3,
    inviteStatus: "Not sent",
    notes: "+2",
  },
  { name: "Bharat", side: "Moksha", group: "Family", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Khatore", side: "Moksha", group: "Family", invitedCount: 4, inviteStatus: "Not sent", notes: "+3" },
  { name: "Jatin", side: "Moksha", group: "Family", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Linda", side: "Moksha", group: "Family", invitedCount: 3, inviteStatus: "Not sent", notes: "+2" },
  { name: "Dee Aunty", side: "Moksha", group: "Family", invitedCount: 2, inviteStatus: "Not sent", notes: "+" },
  {
    name: "Shalini Aunty",
    side: "Moksha",
    group: "Family",
    invitedCount: 2,
    inviteStatus: "Not sent",
    notes: "+",
  },
  { name: "Smeeta", side: "Moksha", group: "Family", invitedCount: 2, inviteStatus: "Not sent", notes: "+" },
  { name: "Sidhu", side: "Moksha", group: "Family", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Solanki", side: "Moksha", group: "Family", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Sameer", side: "Moksha", group: "Family", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Priyanka", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Manraj", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Tommy", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Sophia", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Erin", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  {
    name: "Benny",
    side: "Moksha",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Not sent",
    notes: "+/- 1",
  },
  {
    name: "Sarah",
    side: "Moksha",
    group: "Friends",
    invitedCount: 2,
    inviteStatus: "Not sent",
    notes: "+/- 1",
  },
  { name: "Dharma", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "David", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Anna", side: "Moksha", group: "Friends", invitedCount: 3, inviteStatus: "Not sent", notes: "+2" },
  { name: "Teanna", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Debbie", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Jonathan", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Rose", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Eva", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Sandhya", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Madhu", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "May", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
  { name: "Kristen", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Shenani", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Iman", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Michelle", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Sharity", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Alex", side: "Moksha", group: "Friends", invitedCount: 1, inviteStatus: "Not sent", notes: "" },
  { name: "Will", side: "Moksha", group: "Friends", invitedCount: 2, inviteStatus: "Not sent", notes: "+1" },
].map((guest, index) => ({
  id: `guest-${String(index + 1).padStart(3, "0")}`,
  seedResponse: "Awaiting",
  ...guest,
}));

export function guestKey(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, "-");
}

export function findGuest(name) {
  const key = guestKey(name);
  return GUEST_LIST.find((guest) => guestKey(guest.name) === key);
}
